export default {
  HIST_MAX_LENGTH: 50,

  CONNECTION_UNKNOWN: Number.MIN_VALUE,
  CONNECTION_UP: 1,
  CONNECTION_DOWN: 0,
  CONNECTION_WORKING: 2,
  CONNECTION_ERROR: -1,

  TYPE_LOG: 'LOG',
  TYPE_WARN: 'WARN',
  TYPE_ERROR: 'ERROR',
  TYPE_MESSAGE: 'MSG',
  TYPE_ALL: 'ALL',

  PARAMS_MODE: 'mode',
  PARAMS_SESSION: 'session',
  PARAMS_MODE_IDE: 'ide',
};

